from __future__ import annotations


EXPECTED_META_KEYS = [
    "actual_model",
    "agent",
    "allowed_tools",
    "assistant_content_chars_total",
    "command",
    "copied_session_files",
    "disallowed_tools",
    "error",
    "exit_code",
    "expected_model",
    "forbidden_tool_calls",
    "last_assistant_content_chars",
    "lct_search_conversion_errors",
    "lct_web_tool_effective_calls",
    "member_tool_mode",
    "permission_mode",
    "raw_model_markers",
    "raw_partial_recoverable",
    "response_chars",
    "retried",
    "retry_error",
    "runtime_cwd",
    "session_id",
    "status",
    "stderr_path",
    "stdout_path",
    "subagent_invocation",
    "termination",
    "tool_budget_status",
    "tool_calls",
    "tool_calls_count",
    "tool_output_conversion_errors",
    "tool_result_calls",
    "turns_count",
    "web_tool_effective_calls_count",
    "web_tool_result_call_ids",
    "web_tool_result_calls_count",
]
